### ISSUE TITLE
What is 'mvuepdf' in 'vbgmmpdf.m'?

### ISSUE THREAD

**Issue by wsdqy1234** [lacerbi/vbgmm#1]
![image](https://user-images.githubusercontent.com/53553706/109656857-d1836d80-7b9f-11eb-8050-9fae98ae3d4c.png)
Excuse me, I'm learning the VB-GMM algorithm. And when I compare the 'vbgmmpdf.m' with Section 10.2.3 in PRML, I don't really understand the 'mvuepdf' function while I can not find any explanations in google. So is there any lack for the code?
Thanks for your help!

**Comment by lacerbi** [comment]
You can ignore that - it's not part of VB-GMM. No variational GMM has _negative_ degrees of freedom _df_, so you don't need to worry about that. If you are interested, it was a utility thing for me for another project. If you draw samples / evaluate a pdf with this function setting negative degrees of freedom, it draws samples from / evaluates the pdf of a uniform distribution inside a hyper-ellipsoid (done by the function _mvuepdf.m_, which is not in this toolbox, I should probably add it for completeness).

**Comment by wsdqy1234** [comment]
Thanks very much for your help, I really appreciate it!
