### ISSUE TITLE
Some confusing questions about 'vbgmmgmm.m'.

### ISSUE THREAD

**Issue by wsdqy1234** [lacerbi/vbgmm#2]
Dear lacerbi, I'm learning the way to approximate the variational GMM, and I found some confusing questions about **the modification to the degrees of freedom in Wishart distribution.**
![image](https://user-images.githubusercontent.com/53553706/138086978-c1d69c78-d700-4f74-b3e4-8471bbed4792.png)

In the `mean` case, why `df` should be modified to `nu-nvars-1`? The mean of Wishart distribution should be like:
![image](https://user-images.githubusercontent.com/53553706/138087324-bb40fc7d-5cd6-4684-bb1b-6aca9c04b66f.png)

And I cannot figure out why the computational process in `vbgmmgmm.m` becomes like:
![image](https://user-images.githubusercontent.com/53553706/138088152-6d8cc6c4-711a-4abe-b6d4-80046d7e9003.png)

Are there any mistakes during the calculation? I wonder if I was too thoughtless about the estimation process.

**Comment by lacerbi** [comment]
This code is provided "as is" and I don't guarantee its correctness...

Having said that, as far as I remember the algorithm uses _inverse_ Wishart distributions, not Wishart distributions (as also specified in the snippet above, which mentions the inverse Wishart). The mean and the mode of the _inverse_ Wishart are those in the code: https://en.wikipedia.org/wiki/Inverse-Wishart_distribution
